TRUNCATE TABLE shifts_roles;

INSERT INTO shifts_roles (shift_id, role_id, quantity)
VALUES
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-03' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-04' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-05' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-06' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-07' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-08' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-09' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-10' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-11' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-12' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-13' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-14' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-15' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-16' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-17' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-18' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-19' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-20' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-21' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-22' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-23' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-24' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-25' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-26' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-27' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-28' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-29' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Breakfast'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Line Cook'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Server'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Lunch'), (SELECT id FROM roles WHERE title = 'Bartender'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Head Chef'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Line Cook'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Host'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Server'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Dinner'), (SELECT id FROM roles WHERE title = 'Bartender'), 2),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Manager'), 1),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Bartender'), 3),
  ((SELECT id FROM shifts WHERE date = '2017-04-30' AND name = 'Bar Rush'), (SELECT id FROM roles WHERE title = 'Server'), 2)
